name: facebook_sdk_ios
description: iOS implementation of the facebook_sdk plugin.
repository: https://github.com/nesminnn/facebook_sdk/tree/stable/facebook_sdk_ios

version: 1.0.1

publish_to: "none"

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: facebook_sdk
    platforms:
      ios:
        pluginClass: FacebookSdkPlugin

dependencies:
  flutter:
    sdk: flutter
  facebook_sdk_platform_interface:
    git:
      url: git@github.com:dev-nesmin/facebook_sdk.git
      ref: v1.0.1
      path: facebook_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
  test: ^1.16.3
