name: facebook_sdk
description: Flutter plugin for implementing facebook sdk tools
version: 1.0.1

publish_to: 'none'

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: facebook_sdk_android
      ios:
        default_package: facebook_sdk_ios

dependencies:
  flutter:
    sdk: flutter
  facebook_sdk_platform_interface:
    path: ../facebook_sdk_platform_interface
  facebook_sdk_android:
    path: ../facebook_sdk_android
  facebook_sdk_ios:
    path: ../facebook_sdk_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  plugin_platform_interface: ^2.0.0
